### ISSUE TITLE
你好请教一下这个插件是不是部署了coze-discord-proxy，然后安装了这个插件了就可以直接在cow上面使用了吗

### ISSUE THREAD

**Issue by AnCool-OvO** [wangxyd/nicecoze#1]

**Comment by wangxyd** [comment]
这个插件的目的是优化coze-discord-proxy返回结果的，比如抠取并下载Markdown链接中的图片。
因此首先要确保cow + coze-discord-proxy能正常返回结果，然后再安装该插件！

**Comment by AnCool-OvO** [comment]
> 这个插件的目的是优化coze-discord-proxy返回结果的，比如抠取并下载Markdown链接中的图片。 因此首先要确保cow + coze-discord-proxy能正常返回结果，然后再安装该插件！


好的谢谢啦
